* simsystem

  Simulation for journal [[http://www.eng.auburn.edu/~weishinn/papers/EDBT2013.pdf][An RFID and Particle Filter-Based Indoor
  Spatial Query Evaluation System]].


* Design Brief

1. WalkingGraph

   :Purpose:  Stores the topology of the indoor environment, including
   the readers.  This class provides easy access to vertices and edge
   information.  Basically it's just a collection of data.  This
   walking graph will be setup once in the initialization phase and
   remain constant during the simulation process.

   :Input:    Vertex information (id, coordinates), edge information
   (source and target) and readers information (id, coordinates and
   detection range)

   :Output:   Acess to each vertex coordinate, edge weight and reader
   coordinates.  Also, this class could generate a random window for
   range query.  And what's more, given a reader id, this class
   generates a random point that are: ) on the edge of the graph
   and 2) inside the reader's detection range.

2. SimSystem

   :Purpose:  Randomly generates people's walking trajectory and
   stores the trajectory for later query, including readings by RFID.
   It also provides easy access to every object's positions at any
   time during the simulation.

   :Input:    WalkingGraph, duration of the simulation and the number
   of objects envoled in this simulation, readings detection rate.

   :Output:   Every object's positions at any time and readings.

3. ParticleFilter

   :Purpose:  Do particle filter on generated readings.  This is not
   strictly speaking a particle filter since I made lots of
   compromisations and simplifications during the implementation for
   the sake of time and easiness.

   :Input:    Number of readings taken into consideration.

   :Output:   A hash table containing each object's probability at
   each anchor point.  Zero probability are omitted.
